env: prod
ingress:
    host: enlil.entur.io
configMap:
  firestoreProjectId: ent-enlil-prd
  firestoreDatabaseId: default
  auth0:
    partner:
      url: https://partner.entur.org/
      audience: https://api.entur.io
    client:
      clientId: 8uzKNqUNH4N0Su5DhgFGEOysBxbiLw0j
      tokenUri: https://internal.entur.org/oauth/token
      audience: https://api.entur.io
  baba:
    service: http://baba.prd.entur.internal

  roleAssignmentExtractor: baba
