env: tst
ingress:
    host: enlil.staging.entur.io
configMap:
  firestoreProjectId: ent-enlil-tst
  firestoreDatabaseId: default
  auth0:
    partner:
      url: https://partner.staging.entur.org/
      audience: https://api.staging.entur.io
    client:
      clientId: dlC6Rk3y83oMauMD4MkJVYgyui25oV9x
      tokenUri: https://internal.staging.entur.org/oauth/token
      audience: https://api.staging.entur.io
  baba:
    service: http://baba.tst.entur.internal

  roleAssignmentExtractor: baba
