env: dev
ingress:
  host: enlil.dev.entur.io
configMap:
  firestoreProjectId: ent-enlil-dev
  firestoreDatabaseId: default
  auth0:
    partner:
      url: https://partner.dev.entur.org/
      audience: https://api.dev.entur.io,https://ror.api.dev.entur.io
    client:
      clientId: EnNS93dEDRnhBELa5oubxKd5Vd5WYWM7
      tokenUri: https://internal.dev.entur.org/oauth/token
      audience: https://api.dev.entur.io

  baba:
    service: http://baba.dev.entur.internal

  roleAssignmentExtractor: baba